### ISSUE TITLE
Add support for binary units (KiB, MiB, etc.)

### ISSUE THREAD

**Issue by ggtools** [c2h5oh/datasize#1]
The current system uses decimal factors: 1K = 1000, 1M = 1000, etc. In many cases, it's important to use binary factors: 1K = 1024, 1M = 1024M, etc.

**Comment by c2h5oh** [comment]
It is using binary factors right now - sizes are defined here https://github.com/c2h5oh/datasize/blob/master/datasize.go#L13-L19 as follows:

````go
	B  ByteSize = 1
	KB          = B << 10
	MB          = KB << 10
	GB          = MB << 10
	TB          = GB << 10
	PB          = TB << 10
	EB          = PB << 10
````
`<<` is a left bit shift operator. `<< 10` means shift bits left by 10 positions, which for unsigned integers is an equivalent of multiplying by 2^10 = 1024.

**Comment by ggtools** [comment]
Ooops missread. Sorry.

**Comment by c2h5oh** [comment]
No worries - it's good to see someone else complaining about "marketing megabytes", despite the fact it was unnecessary in this case :-)
