### ISSUE TITLE
UnmarshalText taking string

### ISSUE THREAD

**Issue by JensRantil** [c2h5oh/datasize#3]
Just discovered this library! Nice! Just curious, why does `UnmarshalText` take a byte slice and not a `string` (which would feel more natural since it's text)?

**Comment by c2h5oh** [comment]
It implements TextMarshaler/TextUnmarshaler interfaces ( https://golang.org/pkg/encoding/#TextMarshaler ) - so if you make ByteSize a type of a struct field it will automatically work with json (un)marshaling

**Comment by JensRantil** [comment]
That explains it. Thanks!
